/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JTable;
import modelos.*;
import modelos.fondos.Moninet;

/**
 *
 * @author usuario
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    Consultas consultas = new Consultas();
    Cliente cliente = new Cliente();
    Pagos pagos = new Pagos();
    Paquete paquete = new Paquete();
    Contratos contratos = new Contratos();
    ListaClientes listaClientes = new ListaClientes();
    ListaContratos listaContratos = new ListaContratos();
    ListaPagos listaPagos = new ListaPagos();
    ListaPaquetes listaPaquetes = new ListaPaquetes();

    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        consultas.CargarClientes(tbClientes, cliente, listaClientes.getListaClientes());
        consultas.CargarContratos(tbContratos, contratos, listaContratos.getListaContratos());
        consultas.CargarPago(tbPagos, pagos, listaPagos.getListaPagos());
        consultas.CargarPaquetes(tbPaquetes, paquete, listaPaquetes.getListaPaquetes());
    }

    public JTable getTbClientes() {
        return tbClientes;
    }

    public void setTbClientes(JTable tbClientes) {
        this.tbClientes = tbClientes;
    }

    public JTable getTbContratos() {
        return tbContratos;
    }

    public void setTbContratos(JTable tbContratos) {
        this.tbContratos = tbContratos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tbPanel = new javax.swing.JTabbedPane();
        panelClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnGuardarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        paneContratos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbContratos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtIdContrato = new javax.swing.JTextField();
        txtPaquete = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtIdClienteContratos = new javax.swing.JTextField();
        btnGuardarContratos = new javax.swing.JButton();
        btnActualizarContrato = new javax.swing.JButton();
        btnEliminarContrato = new javax.swing.JButton();
        PanelPagos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPagos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtIdPago = new javax.swing.JTextField();
        txtIdContratoPagos = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtFechaPago = new javax.swing.JTextField();
        btnPagos = new javax.swing.JButton();
        btnActualizarLPagos = new javax.swing.JButton();
        btnEliminarContrato1 = new javax.swing.JButton();
        panelPaquetes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbPaquetes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtIdPaquete = new javax.swing.JTextField();
        txtNombrePaquete = new javax.swing.JTextField();
        txtVelocidad = new javax.swing.JTextField();
        txtPagoMen = new javax.swing.JTextField();
        bntGuardarPaquete = new javax.swing.JButton();
        btnActualizarPaquete = new javax.swing.JButton();
        btnEliminarPaquete = new javax.swing.JButton();
        jPanel1 = new Moninet();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(106, 146, 195));

        tbPanel.setBackground(new java.awt.Color(132, 244, 138));
        tbPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbPanel.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        panelClientes.setBackground(new java.awt.Color(132, 182, 244));
        panelClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CEDULA", "DIRECCION", "TELEFONO", "CORREO"
            }
        ));
        tbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClientes);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Listado de Clientes");

        txtIdCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));

        txtCedula.setBorder(javax.swing.BorderFactory.createTitledBorder("CEDULA"));

        txtDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder("DIERECCION"));

        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("TELEFONO"));

        txtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder("CORREO"));

        btnGuardarCliente.setBackground(new java.awt.Color(85, 214, 69));
        btnGuardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarCliente.setText("Guardar");
        btnGuardarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });

        btnActualizarCliente.setBackground(new java.awt.Color(255, 150, 22));
        btnActualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarCliente.setText("Actualizar");
        btnActualizarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setBackground(new java.awt.Color(255, 36, 8));
        btnEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addComponent(jLabel4))
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelClientesLayout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(btnGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnActualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        tbPanel.addTab("Clientes", panelClientes);

        paneContratos.setBackground(new java.awt.Color(132, 182, 244));
        paneContratos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID CONTRATO", "PAQUETE", "FECHA INICIO", "FECHA FINALIZACION", "ESTADO", "ID CLIENTE"
            }
        ));
        tbContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbContratosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbContratos);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Listado de Contratos");

        txtIdContrato.setBorder(javax.swing.BorderFactory.createTitledBorder("ID CONTRATO"));
        txtIdContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdContratoActionPerformed(evt);
            }
        });

        txtPaquete.setBorder(javax.swing.BorderFactory.createTitledBorder("PAQUETE"));

        txtFechaInicio.setBorder(javax.swing.BorderFactory.createTitledBorder("FECHA INICIO"));

        txtFechaFin.setBorder(javax.swing.BorderFactory.createTitledBorder("FECHA FIN"));
        txtFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFinActionPerformed(evt);
            }
        });

        txtEstado.setBorder(javax.swing.BorderFactory.createTitledBorder("ESTADO"));

        txtIdClienteContratos.setBorder(javax.swing.BorderFactory.createTitledBorder("ID CLIENTE"));

        btnGuardarContratos.setBackground(new java.awt.Color(85, 214, 69));
        btnGuardarContratos.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarContratos.setText("Guardar");
        btnGuardarContratos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardarContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarContratosActionPerformed(evt);
            }
        });

        btnActualizarContrato.setBackground(new java.awt.Color(255, 150, 22));
        btnActualizarContrato.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarContrato.setText("Actualizar");
        btnActualizarContrato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnActualizarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarContratoActionPerformed(evt);
            }
        });

        btnEliminarContrato.setBackground(new java.awt.Color(255, 36, 8));
        btnEliminarContrato.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarContrato.setText("Eliminar");
        btnEliminarContrato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneContratosLayout = new javax.swing.GroupLayout(paneContratos);
        paneContratos.setLayout(paneContratosLayout);
        paneContratosLayout.setHorizontalGroup(
            paneContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContratosLayout.createSequentialGroup()
                .addGroup(paneContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneContratosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneContratosLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel5))
                    .addGroup(paneContratosLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnGuardarContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnActualizarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnEliminarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneContratosLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtIdContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtIdClienteContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneContratosLayout.setVerticalGroup(
            paneContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneContratosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(paneContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdClienteContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(paneContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        tbPanel.addTab("Contratos", paneContratos);

        PanelPagos.setBackground(new java.awt.Color(132, 182, 244));
        PanelPagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PAGO", "ID CONTRATO", "MONTO", "FECHA PAGO"
            }
        ));
        tbPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPagosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbPagos);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Listado de Pagos");

        txtIdPago.setBorder(javax.swing.BorderFactory.createTitledBorder("ID PAGO"));

        txtIdContratoPagos.setBorder(javax.swing.BorderFactory.createTitledBorder("ID CONTRATO"));

        txtMonto.setBorder(javax.swing.BorderFactory.createTitledBorder("MONTO"));

        txtFechaPago.setBorder(javax.swing.BorderFactory.createTitledBorder("FECHA PAGO"));

        btnPagos.setBackground(new java.awt.Color(85, 214, 69));
        btnPagos.setForeground(new java.awt.Color(255, 255, 255));
        btnPagos.setText("Guardar");
        btnPagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });

        btnActualizarLPagos.setBackground(new java.awt.Color(255, 150, 22));
        btnActualizarLPagos.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarLPagos.setText("Actualizar");
        btnActualizarLPagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnActualizarLPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarLPagosActionPerformed(evt);
            }
        });

        btnEliminarContrato1.setBackground(new java.awt.Color(255, 36, 8));
        btnEliminarContrato1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarContrato1.setText("Eliminar");
        btnEliminarContrato1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminarContrato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarContrato1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPagosLayout = new javax.swing.GroupLayout(PanelPagos);
        PanelPagos.setLayout(PanelPagosLayout);
        PanelPagosLayout.setHorizontalGroup(
            PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPagosLayout.createSequentialGroup()
                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPagosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPagosLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel6))
                    .addGroup(PanelPagosLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnActualizarLPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnEliminarContrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPagosLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtIdContratoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPagosLayout.setVerticalGroup(
            PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdContratoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarLPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarContrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        tbPanel.addTab("Pagos", PanelPagos);

        panelPaquetes.setBackground(new java.awt.Color(132, 182, 244));
        panelPaquetes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PAQUETE", "NOMBRE", "VELOCIDAD", "PRECIO MENSUAL"
            }
        ));
        tbPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPaquetesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbPaquetes);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Listado de Paquetes");

        txtIdPaquete.setBorder(javax.swing.BorderFactory.createTitledBorder("ID PAQUETE"));

        txtNombrePaquete.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));

        txtVelocidad.setBorder(javax.swing.BorderFactory.createTitledBorder("VELOCIDAD"));

        txtPagoMen.setBorder(javax.swing.BorderFactory.createTitledBorder("PRECIO MENSUAL"));

        bntGuardarPaquete.setBackground(new java.awt.Color(85, 214, 69));
        bntGuardarPaquete.setForeground(new java.awt.Color(255, 255, 255));
        bntGuardarPaquete.setText("Guardar");
        bntGuardarPaquete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bntGuardarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarPaqueteActionPerformed(evt);
            }
        });

        btnActualizarPaquete.setBackground(new java.awt.Color(255, 150, 22));
        btnActualizarPaquete.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarPaquete.setText("Actualizar");
        btnActualizarPaquete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnActualizarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPaqueteActionPerformed(evt);
            }
        });

        btnEliminarPaquete.setBackground(new java.awt.Color(255, 36, 8));
        btnEliminarPaquete.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPaquete.setText("Eliminar");
        btnEliminarPaquete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelPaquetesLayout = new javax.swing.GroupLayout(panelPaquetes);
        panelPaquetes.setLayout(panelPaquetesLayout);
        panelPaquetesLayout.setHorizontalGroup(
            panelPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaquetesLayout.createSequentialGroup()
                .addGroup(panelPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPaquetesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPaquetesLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaquetesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPaquetesLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(bntGuardarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnActualizarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnEliminarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPaquetesLayout.createSequentialGroup()
                        .addComponent(txtIdPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtNombrePaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtPagoMen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125))
        );
        panelPaquetesLayout.setVerticalGroup(
            panelPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaquetesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPagoMen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntGuardarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        tbPanel.addTab("Paquetes", panelPaquetes);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CRUD MONINET");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Actividades de telecomunicaciones");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inalambricas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addGap(84, 84, 84))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(tbPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntGuardarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarPaqueteActionPerformed
        // TODO add your handling code here:
        paquete.setIdPaquete(txtIdPaquete.getText());
        paquete.setNombre(txtNombrePaquete.getText());
        paquete.setVelocidad(txtVelocidad.getText());
        paquete.setPrecio_mensual(txtPagoMen.getText());
    }//GEN-LAST:event_bntGuardarPaqueteActionPerformed

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        // TODO add your handling code here:
        cliente.setIdCliente(txtIdCliente.getText());
        cliente.setNombre(txtNombre.getText());
        cliente.setDireccion(txtDireccion.getText());
        cliente.setTelefono(txtTelefono.getText());
        cliente.setCorreo(txtCorreo.getText());
        cliente.setCedula(txtCedula.getText());
        consultas.registrarCliente(cliente);
        consultas.CargarClientes(tbClientes, cliente, listaClientes.getListaClientes());
        txtIdCliente.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtCedula.setText("");
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void btnGuardarContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarContratosActionPerformed
        // TODO add your handling code here:
        contratos.setIdCliete(txtIdClienteContratos.getText());
        contratos.setIdContrato(txtIdContrato.getText());
        contratos.setFecha_inicio(txtFechaInicio.getText());
        contratos.setFecha_finalizacion(txtFechaFin.getText());
        contratos.setEstado(txtEstado.getText());
        contratos.setPaquete(txtPaquete.getText());
        consultas.registrarContrato(contratos);
        consultas.CargarContratos(tbContratos, contratos, listaContratos.getListaContratos());

    }//GEN-LAST:event_btnGuardarContratosActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        // TODO add your handling code here:
        pagos.setIdPagos(txtIdPago.getText());
        pagos.setIdContrato(txtIdContratoPagos.getText());
        pagos.setFecha_pago(txtFechaPago.getText());
        pagos.setMonto(txtMonto.getText());
    }//GEN-LAST:event_btnPagosActionPerformed

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
        // TODO add your handling code here:
        cliente.setIdCliente(txtIdCliente.getText());
        cliente.setNombre(txtNombre.getText());
        cliente.setDireccion(txtDireccion.getText());
        cliente.setTelefono(txtTelefono.getText());
        cliente.setCorreo(txtCorreo.getText());
        cliente.setCedula(txtCedula.getText());
        consultas.actualizarCliente(tbClientes, cliente, listaClientes.getListaClientes());
        txtIdCliente.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtCedula.setText("");
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void btnActualizarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarContratoActionPerformed
        // TODO add your handling code here:
        contratos.setIdContrato(txtIdContrato.getText());
        contratos.setPaquete(txtPaquete.getText());
        contratos.setFecha_inicio(txtFechaInicio.getText());
        contratos.setFecha_finalizacion(txtFechaFin.getText());
        contratos.setEstado(txtEstado.getText());
        contratos.setIdCliete(txtIdClienteContratos.getText());

        consultas.actualizarCliente(tbClientes, cliente, listaClientes.getListaClientes());
        txtIdContrato.setText("");
        txtPaquete.setText("");
        txtFechaInicio.setText("");
        txtFechaFin.setText("");
        txtEstado.setText("");
        txtIdClienteContratos.setText("");

    }//GEN-LAST:event_btnActualizarContratoActionPerformed

    private void tbContratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbContratosMouseClicked
        // TODO add your handling code here:
        int row = tbContratos.getSelectedRow();
        txtIdContrato.setText(tbContratos.getValueAt(row, 0).toString());
        txtPaquete.setText(tbContratos.getValueAt(row, 1).toString());
        txtFechaInicio.setText(tbContratos.getValueAt(row, 2).toString());
        txtFechaFin.setText(tbContratos.getValueAt(row, 3).toString());
        txtEstado.setText(tbContratos.getValueAt(row, 4).toString());
        txtIdClienteContratos.setText(tbContratos.getValueAt(row, 5).toString());
    }//GEN-LAST:event_tbContratosMouseClicked

    private void tbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesMouseClicked
        // TODO add your handling code here:
        int row = tbClientes.getSelectedRow();
        txtIdCliente.setText(tbClientes.getValueAt(row, 0).toString());
        txtNombre.setText(tbClientes.getValueAt(row, 1).toString());
        txtCedula.setText(tbClientes.getValueAt(row, 2).toString());
        txtDireccion.setText(tbClientes.getValueAt(row, 3).toString());
        txtTelefono.setText(tbClientes.getValueAt(row, 4).toString());
        txtCorreo.setText(tbClientes.getValueAt(row, 5).toString());
    }//GEN-LAST:event_tbClientesMouseClicked

    private void txtIdContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContratoActionPerformed

    private void txtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinActionPerformed

    private void tbPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPagosMouseClicked
        // TODO add your handling code here:
        int row = tbPagos.getSelectedRow();
        txtIdPago.setText(tbPagos.getValueAt(row, 0).toString());
        txtIdContratoPagos.setText(tbPagos.getValueAt(row, 1).toString());
        txtMonto.setText(tbPagos.getValueAt(row, 2).toString());
        txtFechaPago.setText(tbPagos.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbPagosMouseClicked

    private void btnActualizarLPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarLPagosActionPerformed

        pagos.setIdContrato(txtIdContrato.getText());
        pagos.setIdContrato(txtIdContratoPagos.getText());
        pagos.setMonto(txtMonto.getText());
        pagos.setFecha_pago(txtFechaPago.getText());
//        
        consultas.actualizarPagos(tbPagos, pagos, listaPagos.getListaPagos());
        txtIdContrato.setText("");
        txtIdContratoPagos.setText("");
        txtMonto.setText("");
        txtFechaPago.setText("");

    }//GEN-LAST:event_btnActualizarLPagosActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        int row = tbClientes.getSelectedRow();
        System.out.println("" + row);
        cliente.setIdCliente(tbClientes.getValueAt(row, 0).toString());
        consultas.eliminarCliente(cliente);
        consultas.CargarClientes(tbClientes, cliente, listaClientes.getListaClientes());
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnEliminarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarContratoActionPerformed
        // TODO add your handling code here:
        int row = tbContratos.getSelectedRow();
        contratos.setIdContrato(tbContratos.getValueAt(row, 0).toString());
        consultas.eliminarContrato(contratos);
        consultas.CargarContratos(tbContratos, contratos, listaContratos.getListaContratos());
    }//GEN-LAST:event_btnEliminarContratoActionPerformed

    private void btnEliminarContrato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarContrato1ActionPerformed
        // TODO add your handling code here:
        int row = tbPagos.getSelectedRow();
        pagos.setIdPagos(tbPagos.getValueAt(row, 0).toString());
        consultas.eliminarPago(pagos);
        consultas.CargarPago(tbPagos, pagos, listaPagos.getListaPagos());

    }//GEN-LAST:event_btnEliminarContrato1ActionPerformed

    private void tbPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPaquetesMouseClicked
        // TODO add your handling code here:
        int row = tbPaquetes.getSelectedRow();
        paquete.setIdPaquete(tbPaquetes.getValueAt(row, 0).toString());
        consultas.eliminarPaquete(paquete);
        consultas.CargarPaquetes(tbPaquetes, paquete, listaPaquetes.getListaPaquetes());

    }//GEN-LAST:event_tbPaquetesMouseClicked

    private void btnActualizarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPaqueteActionPerformed
        // TODO add your handling code here:
        paquete.setIdPaquete(txtIdPaquete.getText());
        paquete.setNombre(txtNombrePaquete.getText());
        paquete.setVelocidad(txtVelocidad.getText());
        paquete.setPrecio_mensual(txtPagoMen.getText());
        consultas.actualizarPaquetes(tbPaquetes, paquete, listaPaquetes.getListaPaquetes());
        txtIdPaquete.setText("");
        txtNombrePaquete.setText("");
        txtVelocidad.setText("");
        txtPagoMen.setText("");
    }//GEN-LAST:event_btnActualizarPaqueteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPagos;
    private javax.swing.JButton bntGuardarPaquete;
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnActualizarContrato;
    private javax.swing.JButton btnActualizarLPagos;
    private javax.swing.JButton btnActualizarPaquete;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarContrato;
    private javax.swing.JButton btnEliminarContrato1;
    private javax.swing.JButton btnEliminarPaquete;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JButton btnGuardarContratos;
    private javax.swing.JButton btnPagos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel paneContratos;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelPaquetes;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTable tbContratos;
    private javax.swing.JTable tbPagos;
    private javax.swing.JTabbedPane tbPanel;
    private javax.swing.JTable tbPaquetes;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtFechaPago;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdClienteContratos;
    private javax.swing.JTextField txtIdContrato;
    private javax.swing.JTextField txtIdContratoPagos;
    private javax.swing.JTextField txtIdPago;
    private javax.swing.JTextField txtIdPaquete;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombrePaquete;
    private javax.swing.JTextField txtPagoMen;
    private javax.swing.JTextField txtPaquete;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
